// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bucket_fill.dart';
import 'api/gpu_brush.dart';
import 'api/gpu_composite.dart';
import 'api/image_ops.dart';
import 'api/memory.dart';
import 'api/psd.dart';
import 'api/selection_path.dart';
import 'api/simple.dart';
import 'api/workspace.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceEntry dco_decode_box_autoadd_workspace_entry(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FloodFillPatch dco_decode_flood_fill_patch(dynamic raw);

  @protected
  FloodFillRect dco_decode_flood_fill_rect(dynamic raw);

  @protected
  GpuLayerData dco_decode_gpu_layer_data(dynamic raw);

  @protected
  GpuPoint2D dco_decode_gpu_point_2_d(dynamic raw);

  @protected
  GpuStrokeResult dco_decode_gpu_stroke_result(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<GpuLayerData> dco_decode_list_gpu_layer_data(dynamic raw);

  @protected
  List<GpuPoint2D> dco_decode_list_gpu_point_2_d(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PsdLayer> dco_decode_list_psd_layer(dynamic raw);

  @protected
  List<WorkspaceEntry> dco_decode_list_workspace_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceEntry? dco_decode_opt_box_autoadd_workspace_entry(dynamic raw);

  @protected
  Uint32List? dco_decode_opt_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PsdDocument dco_decode_psd_document(dynamic raw);

  @protected
  PsdLayer dco_decode_psd_layer(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WorkspaceEntry dco_decode_workspace_entry(dynamic raw);

  @protected
  WorkspaceState dco_decode_workspace_state(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceEntry sse_decode_box_autoadd_workspace_entry(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FloodFillPatch sse_decode_flood_fill_patch(SseDeserializer deserializer);

  @protected
  FloodFillRect sse_decode_flood_fill_rect(SseDeserializer deserializer);

  @protected
  GpuLayerData sse_decode_gpu_layer_data(SseDeserializer deserializer);

  @protected
  GpuPoint2D sse_decode_gpu_point_2_d(SseDeserializer deserializer);

  @protected
  GpuStrokeResult sse_decode_gpu_stroke_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<GpuLayerData> sse_decode_list_gpu_layer_data(
    SseDeserializer deserializer,
  );

  @protected
  List<GpuPoint2D> sse_decode_list_gpu_point_2_d(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PsdLayer> sse_decode_list_psd_layer(SseDeserializer deserializer);

  @protected
  List<WorkspaceEntry> sse_decode_list_workspace_entry(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceEntry? sse_decode_opt_box_autoadd_workspace_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint32List? sse_decode_opt_list_prim_u_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PsdDocument sse_decode_psd_document(SseDeserializer deserializer);

  @protected
  PsdLayer sse_decode_psd_layer(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WorkspaceEntry sse_decode_workspace_entry(SseDeserializer deserializer);

  @protected
  WorkspaceState sse_decode_workspace_state(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_workspace_entry(
    WorkspaceEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_flood_fill_patch(
    FloodFillPatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_flood_fill_rect(FloodFillRect self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_layer_data(GpuLayerData self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_point_2_d(GpuPoint2D self, SseSerializer serializer);

  @protected
  void sse_encode_gpu_stroke_result(
    GpuStrokeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_gpu_layer_data(
    List<GpuLayerData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gpu_point_2_d(
    List<GpuPoint2D> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_psd_layer(List<PsdLayer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_workspace_entry(
    List<WorkspaceEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_workspace_entry(
    WorkspaceEntry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_32_strict(
    Uint32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_psd_document(PsdDocument self, SseSerializer serializer);

  @protected
  void sse_encode_psd_layer(PsdLayer self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_entry(
    WorkspaceEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_state(
    WorkspaceState self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
