// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `abr_spacing_to_ratio`, `align4`, `base_name_without_extension`, `can_seek`, `decode_packbits`, `find_sample_count_v6`, `is_done`, `new`, `position`, `reach_8bim_section`, `read_4`, `read_brush_sample`, `read_bytes`, `read_i16`, `read_i32`, `read_u16`, `read_u32`, `read_u8`, `read_ucs2_text`, `read_v12_brush`, `read_v6_brush`, `seek`, `skip`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AbrReader`, `AbrTipMeta`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<AbrFile> abrDecode({required List<int> bytes, String? fileName}) =>
    RustLib.instance.api.crateApiAbrAbrDecode(bytes: bytes, fileName: fileName);

class AbrFile {
  final int version;
  final int subversion;
  final List<AbrTip> tips;

  const AbrFile({
    required this.version,
    required this.subversion,
    required this.tips,
  });

  @override
  int get hashCode => version.hashCode ^ subversion.hashCode ^ tips.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AbrFile &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          subversion == other.subversion &&
          tips == other.tips;
}

class AbrTip {
  final String name;
  final int width;
  final int height;
  final Uint8List alphaMask;
  final int brushType;
  final int? spacingRaw;
  final double? spacing;
  final bool? antialias;
  final int? shortTop;
  final int? shortLeft;
  final int? shortBottom;
  final int? shortRight;
  final int top;
  final int left;
  final int bottom;
  final int right;
  final int depth;
  final int compression;
  final int bytesPerPixel;

  const AbrTip({
    required this.name,
    required this.width,
    required this.height,
    required this.alphaMask,
    required this.brushType,
    this.spacingRaw,
    this.spacing,
    this.antialias,
    this.shortTop,
    this.shortLeft,
    this.shortBottom,
    this.shortRight,
    required this.top,
    required this.left,
    required this.bottom,
    required this.right,
    required this.depth,
    required this.compression,
    required this.bytesPerPixel,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      alphaMask.hashCode ^
      brushType.hashCode ^
      spacingRaw.hashCode ^
      spacing.hashCode ^
      antialias.hashCode ^
      shortTop.hashCode ^
      shortLeft.hashCode ^
      shortBottom.hashCode ^
      shortRight.hashCode ^
      top.hashCode ^
      left.hashCode ^
      bottom.hashCode ^
      right.hashCode ^
      depth.hashCode ^
      compression.hashCode ^
      bytesPerPixel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AbrTip &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          alphaMask == other.alphaMask &&
          brushType == other.brushType &&
          spacingRaw == other.spacingRaw &&
          spacing == other.spacing &&
          antialias == other.antialias &&
          shortTop == other.shortTop &&
          shortLeft == other.shortLeft &&
          shortBottom == other.shortBottom &&
          shortRight == other.shortRight &&
          top == other.top &&
          left == other.left &&
          bottom == other.bottom &&
          right == other.right &&
          depth == other.depth &&
          compression == other.compression &&
          bytesPerPixel == other.bytesPerPixel;
}
