// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

CpuImageBoundsResult cpuImageBoundsRgba({
  required List<int> pixels,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiCpuImageCpuImageBoundsRgba(
  pixels: pixels,
  width: width,
  height: height,
);

class CpuImageBoundsResult {
  final bool ok;
  final Int32List bounds;

  const CpuImageBoundsResult({required this.ok, required this.bounds});

  @override
  int get hashCode => ok.hashCode ^ bounds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CpuImageBoundsResult &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          bounds == other.bounds;
}
