// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clamp_unit_f64_to_f32`, `compositor_cell`

void gpuCompositorInit() =>
    RustLib.instance.api.crateApiGpuCompositeGpuCompositorInit();

Future<Uint32List> gpuCompositeLayers({
  required List<GpuLayerData> layers,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiGpuCompositeGpuCompositeLayers(
  layers: layers,
  width: width,
  height: height,
);

void gpuCompositorDispose() =>
    RustLib.instance.api.crateApiGpuCompositeGpuCompositorDispose();

class GpuLayerData {
  final Uint32List pixels;
  final double opacity;
  final int blendModeIndex;
  final bool visible;
  final bool clippingMask;

  const GpuLayerData({
    required this.pixels,
    required this.opacity,
    required this.blendModeIndex,
    required this.visible,
    required this.clippingMask,
  });

  @override
  int get hashCode =>
      pixels.hashCode ^
      opacity.hashCode ^
      blendModeIndex.hashCode ^
      visible.hashCode ^
      clippingMask.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpuLayerData &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          opacity == other.opacity &&
          blendModeIndex == other.blendModeIndex &&
          visible == other.visible &&
          clippingMask == other.clippingMask;
}
