// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `snapshot`, `workspace_cell`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

WorkspaceState workspaceState() =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceState();

WorkspaceState workspaceReset() =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceReset();

WorkspaceState workspaceOpen({
  required WorkspaceEntry entry,
  required bool activate,
}) => RustLib.instance.api.crateApiWorkspaceWorkspaceOpen(
  entry: entry,
  activate: activate,
);

WorkspaceState workspaceMarkDirty({
  required String id,
  required bool isDirty,
}) => RustLib.instance.api.crateApiWorkspaceWorkspaceMarkDirty(
  id: id,
  isDirty: isDirty,
);

WorkspaceState workspaceSetActive({required String id}) =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceSetActive(id: id);

WorkspaceEntry? workspaceNeighbor({required String id}) =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceNeighbor(id: id);

WorkspaceState workspaceRemove({required String id, String? activateAfter}) =>
    RustLib.instance.api.crateApiWorkspaceWorkspaceRemove(
      id: id,
      activateAfter: activateAfter,
    );

WorkspaceState workspaceReorder({
  required int oldIndex,
  required int newIndex,
}) => RustLib.instance.api.crateApiWorkspaceWorkspaceReorder(
  oldIndex: oldIndex,
  newIndex: newIndex,
);

class WorkspaceEntry {
  final String id;
  final String name;
  final bool isDirty;

  const WorkspaceEntry({
    required this.id,
    required this.name,
    required this.isDirty,
  });

  static Future<WorkspaceEntry> default_() =>
      RustLib.instance.api.crateApiWorkspaceWorkspaceEntryDefault();

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isDirty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDirty == other.isDirty;
}

class WorkspaceState {
  final List<WorkspaceEntry> entries;
  final String? activeId;

  const WorkspaceState({required this.entries, this.activeId});

  static Future<WorkspaceState> default_() =>
      RustLib.instance.api.crateApiWorkspaceWorkspaceStateDefault();

  @override
  int get hashCode => entries.hashCode ^ activeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorkspaceState &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          activeId == other.activeId;
}
